name: Packer Build on Merge

# Controls when the action will run.
# Triggers the workflow on push or pull request events but only for the main branch
on:
  # Workflow is triggered on merges
  push:
    # Workflow will only be triggered for merges on "main" branch
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Initialize packer
      uses: hashicorp/packer-github-actions@master
      with:
        command: init
        target: .
      env:
        PACKER_LOG: 1

    # Ref: https://github.com/marketplace/actions/packer-github-actions
    - name: Build AMI
      uses: hashicorp/packer-github-actions@master
      with:
        command: build
        arguments: >-
          -var source_ami=${{ secrets.SOURCE_AMI }} -var access_key=${{ secrets.ACCESS_KEY }} -var secret_key=${{ secrets.SECRET_KEY }} -var ami_users=["${{ secrets.AWS_DEV }}","${{ secrets.AWS_PROD }}"]
        target: .
      env:
        PACKER_LOG: 1